/***
 * TRIGGER QUE REALIZA EL CALCULO DEL VALOR DEL PRODUCTO POR LA CANTIDAD Y APLICANDO EL DESCUENTO
 * Y LOS IMPUESTOS DE LA FACTURA DESPUES DE REALIZAR LA INSERCION DE UN INVENTARIO
 */
CREATE OR REPLACE  FUNCTION CALCULA_PRECIOS()
RETURNS TRIGGER AS 
$$ 
DECLARE 
	fPrecio FLOAT;
BEGIN 
	fPrecio = (SELECT valor FROM PRODUCTOS WHERE idProducto = NEW.idProducto); --Se obtiene el precio del Producto
	
	UPDATE 	FACTURAS 
	SET		ValorAPagar = valorAPagar + (((NEW.cantidad * fPrecio) + impuestos ) - descuentos)
	WHERE	idFactura = NEW.idFactura;
	RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;


CREATE TRIGGER APLICA_PRECIO
AFTER INSERT ON INVENTARIOS
FOR EACH ROW 
EXECUTE FUNCTION CALCULA_PRECIOS();